name: Publish images to Docker Hub

on:
  push:
    branches: [ develop, release-candidate, master, fix/docker_build ]
  workflow_dispatch: # manually triggered

jobs:
  push_js_ceramic:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Set sha tag
        run: |
          SHA_TAG=$(git rev-parse --short=12 "${{ github.sha }}")
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV
      -
        name: Set master branch tag
        if: ${{ env.BRANCH == 'master' }}
        run: |
          # TODO: change ENV_TAG to 'prod' (and update all other places using 'latest') and use ENV_TAG in place of ENV
          echo "ENV_TAG=latest" >> $GITHUB_ENV
          echo "EVENT_WEBHOOK_URL=${{ secrets.EVENT_WEBHOOK_FIRE }}" >> $GITHUB_ENV
          echo "ENV=prod" >> $GITHUB_ENV
      -
        name: Set rc branch tag
        if: ${{ env.BRANCH == 'release-candidate' }}
        run: |
          echo "ENV_TAG=tnet" >> $GITHUB_ENV
          echo "EVENT_WEBHOOK_URL=${{ secrets.EVENT_WEBHOOK_CLAY }}" >> $GITHUB_ENV
          echo "ENV=tnet" >> $GITHUB_ENV
      -
        name: Set develop branch tag
        if: ${{ env.BRANCH == 'develop' }}
        run: |
          echo "ENV_TAG=dev" >> $GITHUB_ENV
          echo "EVENT_WEBHOOK_URL=${{ secrets.EVENT_WEBHOOK_DEV }}" >> $GITHUB_ENV
          echo "ENV=dev" >> $GITHUB_ENV
      -
        name: Set env tag (default)
        if: ${{ env.ENV_TAG == '' }}
        run: |
          echo "ENV_TAG=dev" >> $GITHUB_ENV
          echo "EVENT_WEBHOOK_URL=${{ secrets.EVENT_WEBHOOK_DEV }}" >> $GITHUB_ENV
          echo "ENV=dev" >> $GITHUB_ENV
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push images
        run: |
          CERAMIC_IMAGE_IDS=["ceramicnetwork/js-ceramic", "${{ steps.login-ecr.outputs.registry }}/ceramic-${{ env.ENV }}"]
          IPFS_IMAGE_IDS=["ceramicnetwork/ipfs-daemon", "${{ steps.login-ecr.outputs.registry }}/js-ipfs-${{ env.ENV }}"]
          TAGS=["${{ env.ENV_TAG }}", "${{ env.SHA_TAG }}", "{{ github.sha }}", "${{ env.BRANCH }}"]

          ./build Dockerfile.daemon $CERAMIC_IMAGE_IDS $TAGS
          ./build Dockerfile.ipfs-daemon $IPFS_IMAGE_IDS $TAGS
#      -
#        name: Publish build event
#        run: |
#          res=$(docker run --rm curlimages/curl curl -X POST ${{ env.EVENT_WEBHOOK_URL }} \
#            -H "Content-Type: application/json" \
#            --user ${{ secrets.AWS_ACCESS_KEY_ID }}:${{ secrets.AWS_SECRET_ACCESS_KEY }} \
#            --aws-sigv4 "aws:amz:${{ secrets.AWS_DEFAULT_REGION }}:execute-api" \
#            -d '
#              {
#                "event_type": "new_ceramic_image",
#                "client_payload":
#                {
#                  "env_tag": "${{ env.ENV_TAG }}",
#                  "sha_tag": "${{ github.sha }}"
#                }
#              }
#            ') || exit 1
#          echo $res
#          if [[ $res != *"Forwarded event"* ]]; then
#            exit 1
#          fi
